feat: add plugin search functionality
danny-avila/LibreChat pull request #1007
Opened 2023-09-27 17:17 UTC by walbercardoso

## Summary

Added plugin search functionality. Useful to search multiples plugins

![image](https://github.com/danny-avila/LibreChat/assets/50842245/f19be8d8-68bc-4f69-aecb-e68803b23176)

![image](https://github.com/danny-avila/LibreChat/assets/50842245/ffa4bb0b-25dd-4861-8c5a-54087f739df7)

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)

## Testing

check if all the modified file works correctly
check the alignment and scaling of the icons

### **Test Configuration**:

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2023-09-27 17:38 UTC, danny-avila requested changes

2023-09-27 17:38 UTC, danny-avila commented on env/conda-meta/history
> +# cmd: /Users/walbercardoso/miniconda3/bin/conda create --prefix ./env
Can you delete this file from the PR?

2023-09-27 17:38 UTC, danny-avila commented
Thanks for the PR! Just one minor issue with the conda file

2023-09-27 17:41 UTC, danny-avila commented
The Plugin Store tests need to be adjusted, too.

2023-09-27 18:25 UTC, walbercardoso commented on env/conda-meta/history
> +# cmd: /Users/walbercardoso/miniconda3/bin/conda create --prefix ./env
Done

2023-09-28 14:41 UTC, Berry-13 commented
There is a bug that, when it doesn't find anything, the plugin window becomes smaller.
I can't change the plugin page (only page 1 works).
The search bar doesn't adapt to the theme.

I'll try to fix it later

2023-09-28 17:54 UTC, walbercardoso commented
Hi Berry. I just fixed. Can you try again?

2023-09-28 18:37 UTC, Berry-13 commented
@walbercardoso now the page work! do you mind if I make a commit that improves other things too?

2023-09-28 18:45 UTC, walbercardoso commented
@Berry-13 Sure. Go ahead

2023-09-28 19:09 UTC, Berry-13 commented
OK I mess up with the commits, but the Dialog works perfectly. I've also added three translations and a new test for the search function. I think this PR is good to go. @walbercardoso thanks for your hard work and quick responses! Just let us know when you think it's ready

2023-09-28 19:15 UTC, walbercardoso commented
Thanks @Berry-13 . I think its good to go now.
I'm happy to have contributed.

2023-10-11 20:38 UTC, danny-avila approved these changes

2023-10-11 20:38 UTC, merged