style(Sidebar) added ToolTip
danny-avila/LibreChat pull request #1038
Opened 2023-10-10 19:23 UTC by Berry-13

## Summary

added tooltip sidebar support

### when sidebar is open

![Screenshot 2023-10-09 231155](https://github.com/danny-avila/LibreChat/assets/81851188/b8414ba3-ba25-4b5d-a177-64b74a2fa840)

### when sidebar is close

![Screenshot 2023-10-09 231201](https://github.com/danny-avila/LibreChat/assets/81851188/b45b4fa0-5d76-4029-a41a-0bdfc5a63309)

## Change Type

- [x] Accessibility

## Testing

check if it properly works

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2023-10-10 20:48 UTC, danny-avila requested changes

2023-10-10 20:48 UTC, danny-avila commented on client/src/components/Nav/Nav.tsx
> +        <>
remove empty brackets, not needed when there is a parent (Tooltip)

2023-10-10 20:48 UTC, danny-avila commented on client/src/components/Nav/Nav.tsx
> +          ></div>
make this 

```
        <div
          className={'nav-mask' + (navVisible ? ' active' : '')}
          onClick={toggleNavVisible}
        />
```

and remove the empty brackets as before

2023-10-10 20:48 UTC, danny-avila commented
Thanks @Berry-13 lgtm! I tested and works well, no typescript issues, just a few minor syntax issues

2023-10-10 20:51 UTC, danny-avila commented
also feel free to start making branches on the main repo so we can run playwright tests on your PRs

2023-10-10 21:16 UTC, Berry-13 commented
> Thanks @Berry-13 lgtm! I tested and works well, no typescript issues, just a few minor syntax issues

Done! In the meantime, I've also made some improvements to make the code more readable

2023-10-11 01:10 UTC, danny-avila approved these changes

2023-10-11 01:11 UTC, merged