feat: ban-user command
danny-avila/LibreChat pull request #1121
Opened 2023-10-29 21:38 UTC by Berry-13

### created a command `npm run ban-user` to ban a specific user "theoretically" for 1 month

![image](https://github.com/danny-avila/LibreChat/assets/81851188/f5b022a1-1b36-400e-9098-d7c167453155)

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Testing

1. controllo da diverse browser con diversi IP se l'utente è stato bannato e che non può inviare piu messaggi

NOTE: When the account is banned, if I restart the server I can log back in but the moment I write a message and send it, it kicks me out and doesn't send the message

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2023-10-30 14:01 UTC, danny-avila commented
why not also allow a user input for the duration?

2023-11-02 10:48 UTC, Berry-13 commented
> Why not also allow a user input for the duration?

Because I can't find a way to specify the time

2023-11-03 03:56 UTC, techwithanirudh commented
> > Why not also allow a user input for the duration?
> 
> Because I can't find a way to specify the time

```
 const errorMessage = {
    type: 'concurrent',
    violation_count: 20,
    user_id: user._id,
    prev_count: 0,
    duration: 1000 * 60 * 60 * 24 * 7,
  };

  await banViolation(req, res, errorMessage);
```

You're specifying the duration here, I believe.

2023-11-03 12:58 UTC, Berry-13 commented
> > > Why not also allow a user input for the duration?
> > 
> > 
> > Because I can't find a way to specify the time
> 
> ```
>  const errorMessage = {
>     type: 'concurrent',
>     violation_count: 20,
>     user_id: user._id,
>     prev_count: 0,
>     duration: 1000 * 60 * 60 * 24 * 7,
>   };
> 
>   await banViolation(req, res, errorMessage);
> ```
> 
> You're specifying the duration here, I believe.

Yeah, but I'm perma banning, that 'duration' doesn't work or it is being ignored by something else.

2023-11-03 17:12 UTC, fuegovic approved these changes
tested, ban + duration of the ban are working

2023-11-03 18:34 UTC, danny-avila commented on package-lock.json
please remove changes to package-lock.json

2023-11-03 18:35 UTC, danny-avila requested changes
please remove changes to package-lock.json

Bumping dependencies should be in a standalone PR

2023-11-03 19:58 UTC, Berry-13 commented
> please remove changes to package-lock.json
> 
> Bumping dependencies should be in a standalone PR

Sorry, I had added everything and hadn't noticed.

2023-11-04 15:38 UTC, danny-avila approved these changes

2023-11-04 15:38 UTC, merged