style: update graphics (WIP)
danny-avila/LibreChat pull request #1138
Opened 2023-11-04 18:20 UTC by Berry-13

# update new graphics

## NavLinks (changed scale, position and icons)

### before:

![image](https://github.com/danny-avila/LibreChat/assets/81851188/155081da-e0a7-4cf0-9176-4f2b41e0a6a1)

### after:

![image](https://github.com/danny-avila/LibreChat/assets/81851188/423e98fd-2135-406a-994a-78ca19167c47)

## Settings (changed icons)

### before:

![image](https://github.com/danny-avila/LibreChat/assets/81851188/96e324e8-8ffa-416c-ad2f-69458d43f330)

### after:

![image](https://github.com/danny-avila/LibreChat/assets/81851188/630250ab-7f19-432b-b914-e0255c6197be)

## Bug fix:
- [x] removed unnecessary svg icon

# Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Style

# Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2023-11-15 12:34 UTC, danny-avila requested changes

2023-11-15 12:34 UTC, danny-avila commented on client/src/components/Input/SetKeyDialog/SetKeyDialog.tsx
> +              className={cn()}
```suggestion
             // className={cn()} // <-- remove empty cn call
```

2023-11-15 12:34 UTC, danny-avila commented on client/src/components/Input/TextChat.tsx
> +                  hasText={hasText}
this component is going to be deprecated soon, but im curious what the `hasText` change is for though, not really apparent

2023-11-15 16:39 UTC, Berry-13 commented on client/src/components/Input/TextChat.tsx
> +                  hasText={hasText}
hasText is used to check if there is any text in the input, so as to change the color of the button.

![image](https://github.com/danny-avila/LibreChat/assets/81851188/2c6ff122-c7e0-46fb-bae1-955fe801a6e7)

2023-11-16 13:39 UTC, danny-avila approved these changes

2023-11-16 13:42 UTC, merged