🌍: Portuguese and Spanish Translation - Update
danny-avila/LibreChat pull request #1202
Opened 2023-11-19 11:17 UTC by itzraiss

# Pull Request Template

### ⚠️ Before Submitting a PR, read the [Contributing Docs](./CONTRIBUTING.md) in full!

## Summary

🌍: Update and fix the Spanish and Brazilian Portuguese languages for new features, as well as make the language more natural

## Change Type

Please delete any irrelevant options.

- [ ] Translation Update / fix

2023-11-19 11:19 UTC, Berry-13 requested changes

2023-11-19 11:19 UTC, Berry-13 commented on client/src/localization/languages/Es.tsx
> +com_nav_lang_arabic: 'العربية',
and remove these

2023-11-19 11:19 UTC, Berry-13 commented on client/src/localization/languages/Br.tsx
> +  com_nav_lang_arabic: 'العربية',
remove these translations

2023-11-19 11:24 UTC, itzraiss commented on client/src/localization/languages/Br.tsx
> +  com_nav_lang_arabic: 'العربية',
Done

2023-11-19 11:41 UTC, Berry-13 approved these changes
Thank you!

2023-11-19 21:03 UTC, danny-avila approved these changes

2023-11-19 21:03 UTC, merged

2023-11-22 13:17 UTC, danny-avila commented
for your information, there were duplicate keys included in this PR. Please make sure to delete the old translations you are replacing, or replace them in place.

```
[plugin:vite:esbuild] Duplicate key "com_endpoint_google_topk" in object literal
143|    com_endpoint_default: 'predeterminado',
144|    com_endpoint_top_p: 'Top P',
145|    com_endpoint_google_topk:
   |    ^
146|      'Top-k cambia cómo el modelo selecciona tokens para la salida. Un top-k de 1 significa que el token seleccionado es el más probable entre todos los tokens del vocabulario del modelo (también llamado decodificación codiciosa), mientras que un top-k de 3 significa que el siguiente token se selecciona entre los 3 tokens más probables (usando la temperatura).',
147|    com_endpoint_google_maxoutputtokens:

[plugin:vite:esbuild] Duplicate key "com_endpoint_google_maxoutputtokens" in object literal
145|    com_endpoint_google_topk:
146|      'Top-k cambia cómo el modelo selecciona tokens para la salida. Un top-k de 1 significa que el token seleccionado es el más probable entre todos los tokens del vocabulario del modelo (también llamado decodificación codiciosa), mientras que un top-k de 3 significa que el siguiente token se selecciona entre los 3 tokens más probables (usando la temperatura).',
147|    com_endpoint_google_maxoutputtokens:
   |    ^
148|      'Número máximo de tokens que se pueden generar en la respuesta. Especifica un valor menor para respuestas más cortas y un valor mayor para respuestas más largas.',
149|    com_endpoint_google_custom_name_placeholder: 'Establece un nombre personalizado para PaLM2',

[plugin:vite:esbuild] Duplicate key "com_endpoint_google_custom_name_placeholder" in object literal
147|    com_endpoint_google_maxoutputtokens:
148|      'Número máximo de tokens que se pueden generar en la respuesta. Especifica un valor menor para respuestas más cortas y un valor mayor para respuestas más largas.',
149|    com_endpoint_google_custom_name_placeholder: 'Establece un nombre personalizado para PaLM2',
   |    ^
150|    com_endpoint_prompt_prefix_placeholder: 'Establece instrucciones o contexto personalizados. Se ignora si está vacío.',
151|    com_endpoint_custom_name: 'Nombre personalizado',

[plugin:vite:esbuild] Duplicate key "com_endpoint_custom_name" in object literal
149|    com_endpoint_google_custom_name_placeholder: 'Establece un nombre personalizado para PaLM2',
150|    com_endpoint_prompt_prefix_placeholder: 'Establece instrucciones o contexto personalizados. Se ignora si está vacío.',
151|    com_endpoint_custom_name: 'Nombre personalizado',
   |    ^
152|    com_endpoint_prompt_prefix: 'Prefijo de indicación',
153|    com_endpoint_temperature: 'Temperatura',

[plugin:vite:esbuild] Duplicate key "com_endpoint_prompt_prefix" in object literal
150|    com_endpoint_prompt_prefix_placeholder: 'Establece instrucciones o contexto personalizados. Se ignora si está vacío.',
151|    com_endpoint_custom_name: 'Nombre personalizado',
152|    com_endpoint_prompt_prefix: 'Prefijo de indicación',
   |    ^
153|    com_endpoint_temperature: 'Temperatura',
154|    com_endpoint_default: 'predeterminado',

[plugin:vite:esbuild] Duplicate key "com_endpoint_temperature" in object literal
151|    com_endpoint_custom_name: 'Nombre personalizado',
152|    com_endpoint_prompt_prefix: 'Prefijo de indicación',
153|    com_endpoint_temperature: 'Temperatura',
   |    ^
154|    com_endpoint_default: 'predeterminado',
155|    com_endpoint_top_p: 'Top P',

[plugin:vite:esbuild] Duplicate key "com_endpoint_default" in object literal
152|    com_endpoint_prompt_prefix: 'Prefijo de indicación',
153|    com_endpoint_temperature: 'Temperatura',
154|    com_endpoint_default: 'predeterminado',
   |    ^
155|    com_endpoint_top_p: 'Top P',
156|    com_endpoint_top_k: 'Top K',

[plugin:vite:esbuild] Duplicate key "com_endpoint_top_p" in object literal
153|    com_endpoint_temperature: 'Temperatura',
154|    com_endpoint_default: 'predeterminado',
155|    com_endpoint_top_p: 'Top P',
   |    ^
156|    com_endpoint_top_k: 'Top K',
157|    com_endpoint_max_output_tokens: 'Tokens máximos de salida',
```