🗣️ feat: STT & TTS (WIP)
danny-avila/LibreChat pull request #1603
Opened 2024-01-20 22:44 UTC by Berry-13

## Summary

WIP

thank you @bsu3338 for the integrated browser STT & TTS

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2024-01-20 23:29 UTC, bsu3338 commented
@Berry-13 Thank-you for finishing it. I was just about to take another look at it, but am glad you are. Congrats to the whole team on the github trending!

2024-01-20 23:32 UTC, Berry-13 commented
> @Berry-13 Thank-you for finishing it. I was just about to take another look at it, but am glad you are. Congrats to the whole team on the github trending!

you're welcome 😊

2024-02-05 12:36 UTC, mpinta commented on client/src/hooks/useSpeechToText.tsx
> +    if (e.shiftKey && e.altKey && e.key === 'L') {
Hello everybody!

I tested the feature and found that the key combination to activate STT doesn't work on macOS. The thing is that the "Shift+Alt+L" combination produces the character "Ò", which then fails to match in `e.key === 'L'`.

Since `KeyboardEvent.keyCode` is deprecated, the "L" key shouldn't be matched with `e.keyCode === 76`. A possible solution is `e.code === 'KeyL'`. I suggest you check out if `KeyboardEvent.code` matches your desired browser compatibility [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#browser_compatibility) 🙂

2024-02-05 18:00 UTC, Berry-13 commented on client/src/hooks/useSpeechToText.tsx
> +    if (e.shiftKey && e.altKey && e.key === 'L') {
oh, thank you, I will fix that

2024-02-26 10:41 UTC, mynumu commented on client/src/hooks/useSpeechToText.tsx
> +    if (e.shiftKey && e.altKey && e.key === 'L') {
hello - is there an ETA for this to be added to main?? Or shall we test this thanks

2024-02-29 21:26 UTC, Berry-13 commented on client/src/hooks/useSpeechToText.tsx
> +    if (e.shiftKey && e.altKey && e.key === 'L') {
Hey there! Things have been pretty busy lately, so I don't have a specific ETA. I need to make a final adjustment to the PR and it'll be good to go. I hope it won't take more than 2 weeks

2024-03-05 15:52 UTC, danny-avila commented
Is this still in draft?

2024-03-05 15:53 UTC, Berry-13 commented
> Is this still in draft?

yes

2024-03-16 03:35 UTC, Fakamoto commented
Good that you added azure stt from @szkiu !

Now what are we waiting to merge this?

Any way we can help?

2024-03-16 09:48 UTC, Berry-13 commented
> Good that you added azure stt from @szkiu !
> 
> Now what are we waiting to merge this?
> 
> Any way we can help?

there are still some things to add, fix merge conflicts, and also fix the TTS since right now it's not sending correctly the buffer to the client

2024-03-25 19:09 UTC, virtuman commented
Would be nice to add deepgram.io , it has whisper models as well, but it's much faster and 200 minutes per month free

2024-03-25 21:45 UTC, Berry-13 commented
> Would be nice to add deepgram.io , it has whisper models as well, but it's much faster and 200 minutes per month free

sure, I'll take a look at this but in another PR. I already want to add the Google cloud STT & TTS, I'll try to add this too

2024-03-28 08:12 UTC, twmht commented
@Berry-13 
Any update on this PR?

2024-03-28 12:18 UTC, Berry-13 commented
> @Berry-13 Any update on this PR?

Hey there! the PR is all set to go! The only thing left is to test out the Azure Whisper feature, but I'm still waiting on the key for that. Unfortunately, until I have it, there isn't much more I can do at the moment. @danny-avila mentioned he'll be reviewing it within the next few weeks

2024-04-01 14:11 UTC, danny-avila requested changes

2024-04-01 14:11 UTC, danny-avila commented on client/src/components/Chat/Input/ChatForm.tsx
> +  const { data: startupConfig } = useGetStartupConfig();
Please move all STT/TTS logic into its own custom hook(s) under ~/hooks/input

2024-04-01 14:11 UTC, danny-avila commented on client/src/components/Chat/Messages/HoverButtons.tsx
> +  const isMouseDownRef = useRef(false);
Please move all STT/TTS logic into its own custom hook(s) under ~/hooks/input


Note, this should be separate from the hooks for ChatForm, and other areas. Separate/organize the logic as much as possible

2024-04-01 14:11 UTC, danny-avila commented on client/src/hooks/useSpeechToText.tsx
> +import { useState, useEffect } from 'react';
move under input directory and follow the patterns for exporting set by other hooks within directories

2024-04-01 14:11 UTC, danny-avila commented on client/src/components/Chat/Input/ChatForm.tsx
> +  const { data: startupConfig } = useGetStartupConfig();
I understand you are already using hooks, but the useEffects and variable initialization need to happen within them, creating a separate hook if necessary

2024-04-01 14:11 UTC, danny-avila commented on client/src/components/Chat/Messages/HoverButtons.tsx
> +  const isMouseDownRef = useRef(false);
as stated before, I understand you are already using hooks, but the useEffects and variable initialization need to happen within them, creating a separate hook if necessary

2024-04-01 14:12 UTC, danny-avila commented on client/src/components/Chat/Messages/HoverButtons.tsx
> +  const isMouseDownRef = useRef(false);
The point is to reduce the number of lines as much as possible when importing/using logic that is not a primary function for the component you are introducing it to.

2024-04-01 14:25 UTC, danny-avila commented
Great job @Berry-13 

My initial comments are just form glancing at the code through github.

I will do a more thorough review once you make the changes and I pull down the code for testing.

2024-04-06 09:47 UTC, kneelesh48 commented
Eagerly waiting for this PR

2024-04-07 00:23 UTC, mf commented
Same here. Would really help orgs that cater to employees with disabilities or ADA compliance requirements

2024-04-10 01:02 UTC, luvwinnie commented
Is this possible to integrate whisper load locally or using inference framework such as triton inference server?

2024-04-12 19:55 UTC, berry-13 commented
> Is this possible to integrate whisper load locally or using inference framework such as triton inference server?

oops, not sure why I missed this ping. You can just run Whisper locally with LocalAI and then pass the URL into the `librechat.yaml` file

2024-04-23 02:33 UTC, xixingya commented
Eagerly waiting for this PR

2024-04-23 13:15 UTC, bpawnzZ commented
I built this branch and have the button there as shown in the pic and i can speak and it outputs to the console correctly.  However, I can figure out how to get ElevenLabs api working so that my ai can talk back.  I see the button to press under the message but it has no effect..  Can you give me some directions on how to finish getting this going??  Thank you!

2024-04-23 18:06 UTC, Fakamoto commented
Benefit from merging the feature now to main > Benefit from waiting 1 more month to add new features

2024-04-23 18:12 UTC, bpawnzZ commented
> Benefit from merging the feature now to main > Benefit from waiting 1 more month to add new features

thats no fun man...  Lol. I guess i hear you though. Props on this feature however!.  Yall are doing a good job with this project

2024-04-23 19:39 UTC, danny-avila commented
> Benefit from merging the feature now to main > Benefit from waiting 1 more month to add new features

The benefit of the current plan is less maintenance and work on a new feature which would delay planned updates.

2024-04-23 19:40 UTC, danny-avila commented
I also advise against merging this into a fork because there are changes yet to be done in this PR

2024-04-25 20:32 UTC, danny-avila commented
Thank you @berry-13 for continuing to work on this

2024-04-25 21:13 UTC, XHyperDEVX commented
@kneelesh48 
@mf 
@xixingya 
@Fakamoto 

hello you four. i don't want (didn't want) to wait any longer either, so i downloaded the branch locally, built it myself and imported the image into my docker system. done.

if any of you use docker, i have uploaded the image to a filehoster (unfortunately it only works for 21 days and max. 50 downloads). So if any of you have no idea how docker images work but would like to use this wonderful tts/sst function and have it running on docker: [Here](https://filetransfer.io/data-package/h7SC6jZ5#link) you can download the latest TTS/SST Librechat image that I have created. (note that this image will NOT be updated and should only be a temporary solution until danny merges).

I hope I can help some of you.

I can say: TTS/SST works great!

For those who want to do it themselves:
```
git clone -b Speech-to-Text https://github.com/danny-avila/LibreChat.git
cd LibreChat
(apt install docker.io)
docker build -t librechat_tts .
(docker save --output /path/to/librechat_tts.tar librechat_tts)
```
...and that's it.
you only have to do the last step in () if you want to export the image. you will then get the same image as you get from my link above.

(berry and danny, if this is a problem please delete this comment)

have a nice day guys :)

2024-04-26 03:37 UTC, xixingya commented
> @kneelesh48 @mf @xixingya @Fakamoto
> 
> hello you four. i don't want (didn't want) to wait any longer either, so i downloaded the branch locally, built it myself and imported the image into my docker system. done.
> 
> if any of you use docker, i have uploaded the image to a filehoster (unfortunately it only works for 21 days and max. 50 downloads). So if any of you have no idea how docker images work but would like to use this wonderful tts/sst function and have it running on docker: [Here](https://filetransfer.io/data-package/h7SC6jZ5#link) you can download the latest TTS/SST Librechat image that I have created. (note that this image will NOT be updated and should only be a temporary solution until danny merges).
> 
> I hope I can help some of you.
> 
> I can say: TTS/SST works great!
> 
> For those who want to do it themselves:
> 
> ```
> git clone -b Speech-to-Text https://github.com/danny-avila/LibreChat.git
> cd LibreChat
> (apt install docker.io)
> docker build -t librechat_tts .
> (docker save --output /path/to/librechat_tts.tar librechat_tts)
> ```
> 
> ...and that's it. you only have to do the last step in () if you want to export the image. you will then get the same image as you get from my link above.
> 
> (berry and danny, if this is a problem please delete this comment)
> 
> have a nice day guys :)

thanks

2024-04-26 08:27 UTC, berry-13 commented
> PS. Is there any forms of TTS that is working you could give me a hint on? Even if they are beta solutions

thanks! yes,

**Local:**
- TTS: Piper
- STT: Whisper-Base

**External (paid):**
- TTS: ElevenLabs
- STT: OpenAI Whisper

2024-04-27 21:31 UTC, XHyperDEVX commented
@berry-13 when do you think you will be completely finished with this pr so that it is ready to merge?

2024-04-27 21:34 UTC, berry-13 commented
> @berry-13 when do you think you will be completely finished with this pr so that it is ready to merge?

when I commit, it means the changes are ready for merging. But since Danny mentioned he's going to refactor and fix some things, I'll continue until he begins reviewing it. Besides, I'll be working with him to ensure the Conversation Mode works properly since it's only partially functional at the moment

2024-05-07 17:44 UTC, kneelesh48 commented
@berry-13 have you added support for Azure and GCP TTS in this PR?
Those are the OG TTS models. Also, eleven labs is expensive and I don't like their subscription pricing model.

2024-05-08 14:53 UTC, berry-13 commented
> @berry-13 have you added support for Azure and GCP TTS in this PR? Those are the OG TTS models. Also, eleven labs is expensive and I don't like their subscription pricing model.

I personally use Elevenlabs. It has websocket support and one of the best TTS models out there. I can't add Azure TTS because I don't have a key (I can't). Google TTS is planned, and I'm working on adding support for multiple providers. I'll also be adding some other providers in the future

2024-05-11 16:12 UTC, kneelesh48 commented
@berry-13 I can provide you an azure key

2024-05-16 08:52 UTC, bnord01 commented
FYI: The current implementation crashes the whole application on login in Firefox.

```
Unexpected Application Error!
SpeechRecognition is not a constructor

initializeSpeechRecognition@http://localhost:3090/src/hooks/Input/useSpeechToTextBrowser.ts:2127:25
useSpeechToTextBrowser/<@http://localhost:3090/src/hooks/Input/useSpeechToTextBrowser.ts:2150:25
``

2024-05-16 09:25 UTC, berry-13 commented
> SpeechRecognition

oh, thank you for reporting this!
I'm going to fix this now

2024-05-21 12:09 UTC, danny-avila commented
For those patiently following this feature, we are looking to finish this by end of the week

2024-05-23 05:26 UTC, closed without merging