feat(chore): add missing translations in Ru.tsx
danny-avila/LibreChat pull request #2061
Opened 2024-03-11 13:13 UTC by virtuman

# Pull Request Template

## Summary

Add missing translations in Ru.tsx

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

tested by viewing the pages on desktop and mobile

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] New documents have been locally validated with mkdocs

2024-03-12 16:14 UTC, danny-avila commented
`com_nav_my_files` already exists for "My Files."

Please use this instead and remove the additional field for the same translation, and use `com_nav_my_files` instead, then I will merge.

2024-03-12 16:14 UTC, danny-avila requested changes

2024-03-12 16:14 UTC, danny-avila commented on client/src/components/Chat/Input/Files/FilesView.tsx
> +            {localize('com_ui_my_files')}
use `com_nav_my_files`

2024-03-12 16:14 UTC, danny-avila commented on client/src/components/Chat/Input/Files/FilesView.tsx
> +import { useLocalize } from '~/hooks';
please move useLocalize import before utils import

2024-03-12 16:14 UTC, danny-avila commented on client/src/localization/languages/Eng.tsx
> +  com_ui_my_files: 'My Files',
remove

2024-03-12 16:14 UTC, danny-avila commented on client/src/localization/languages/Ru.tsx
> +  com_ui_my_files: 'Мои файлы',
remove

2024-03-13 20:51 UTC, virtuman reviewed
all comments fixed

2024-03-13 20:51 UTC, virtuman commented on client/src/components/Chat/Input/Files/FilesView.tsx
> +import { useLocalize } from '~/hooks';
done

2024-03-14 13:08 UTC, danny-avila approved these changes

2024-03-14 14:19 UTC, virtuman commented
when do you think it will be merged?

2024-03-14 15:26 UTC, merged

2024-03-14 15:27 UTC, danny-avila commented
> when do you think it will be merged?

I just merged it, meant to do so earlier. Thank you!