🔧 fix(openidStrategy): fixed avatar not persistent
danny-avila/LibreChat pull request #2065
Opened 2024-03-11 14:49 UTC by Berry-13

## Summary

fixed #2056 

## Change Type

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Testing

tested with AWS cognito

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] New documents have been locally validated with mkdocs

2024-03-11 14:55 UTC, danny-avila requested changes

2024-03-11 14:55 UTC, danny-avila commented on api/strategies/openidStrategy.js
> +    ? `${given_name} ${family_name}`
Please don't nest ternary operators

2024-03-11 15:13 UTC, Berry-13 commented on api/strategies/openidStrategy.js
> +    ? `${given_name} ${family_name}`
is now cleaner?

2024-03-12 12:47 UTC, Berry-13 commented
want, don't merge this PR

2024-04-04 18:58 UTC, Berry-13 commented
closing this since we should prioritize a more robust solution by addressing the current shortcomings in handling the avatar within OpenID. The current implementation is not optimal and requires improvement

2024-04-04 18:58 UTC, closed without merging