Add CONSOLE_JSON for deploying to GCP K8S env
danny-avila/LibreChat pull request #2146
Opened 2024-03-20 12:55 UTC by idachev

# Pull Request Template

## Summary

Added CONSOLE_JSON to start dump the logs as UTC timestamp and as json.

## Change Type

Please delete any irrelevant options.

- [] New feature (non-breaking change which adds functionality)

## Testing
Before:
![image](https://github.com/danny-avila/LibreChat/assets/464458/596e30f2-6369-4546-89ad-fe7efa98c1cc)

After:
![image](https://github.com/danny-avila/LibreChat/assets/464458/74bf6c5b-5318-436f-9f36-0c2be003f40d)

## Checklist

Please delete any irrelevant options.

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings

2024-03-21 12:11 UTC, danny-avila commented
I noticed you added docker build scripts, can you explain them a bit? I don't have issues with including but noticed you didn't mention them.

Thanks for the PR!

2024-03-26 05:45 UTC, idachev-shipcars commented
> I noticed you added docker build scripts, can you explain them a bit? I don't have issues with including but noticed you didn't mention them.
> 
> Thanks for the PR!

Yep, I use these to build the docker and push it to the custom Google GCP docker registry. You can pass arguments where to push. I know there are scripts to do this in GitHub Actions, but these are for the official repo and cannot be easily used to push to a custom registry.

2024-03-27 12:23 UTC, danny-avila approved these changes

2024-03-27 12:31 UTC, danny-avila requested changes

2024-03-27 12:31 UTC, danny-avila commented on package-lock.json
If you can, remove package-lock.json from the PR. I believe you might have to use `git reset`.

2024-03-27 13:58 UTC, idachev commented on package-lock.json
Removed

2024-03-27 14:02 UTC, danny-avila approved these changes

2024-03-27 14:07 UTC, merged