Feat/contributors guideline
danny-avila/LibreChat pull request #216
Opened 2023-05-08 02:13 UTC by ocontant

Draft of contributing guide.

2023-05-08 18:45 UTC, danorlando requested changes
This is perfect. Just need to add the one additional sentence about including the steps to test the PR and then we're good to go!

2023-05-08 18:45 UTC, danorlando commented on CONTRIBUTING.md
> +4. Submit a pull request with a clear and concise description of your changes and the reasons behind them.
Also include steps to test the PR. "Submit a pull request with a clear and concise description of your changes and the reasons behind them. Be sure to include the steps to test the PR.

2023-05-08 23:30 UTC, fuegovic commented on CONTRIBUTING.md
> +4. Submit a pull request with a clear and concise description of your changes and the reasons behind them.
For reference, I've put a big note in the top of the PR section in the version I have (and I also ha a doc specifically about testing procedure)

```
## 3. Pull Request Process


### Note: Submit a pull request with a clear and concise description of your changes and the reasons behind them. Be sure to include the steps to test the PR.

1. Ensure any install or build dependencies are removed before the end of the layer when doing a
   build.
2. Update the README.md with details of changes to the interface, this includes new environment
   variables, exposed ports, useful file locations and container parameters.
3. Increase the version numbers in any examples files and the README.md to the new version that this
   Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).

Ensure that your changes meet the following criteria when submitting a pull request:
- All tests pass.
- The code is well-formatted and adheres to our coding standards.
- The commit history is clean and easy to follow. (Use Squash to clean your commit history)
- The pull request description clearly outlines the changes and the reasons behind them.
```

2023-05-09 18:40 UTC, fuegovic commented on CONTRIBUTING.md
> +4. Submit a pull request with a clear and concise description of your changes and the reasons behind them.
@danorlando , better check the updated one from the new docs structure to see if it's ok. I updated it like previously shown⬆️. If there are changes to be made, they need to be done from the updated branch to not break anything

2023-05-09 19:24 UTC, danorlando commented
We can close this PR since the contents of this file was added to the new document structure by @fuegovic

2023-05-09 19:24 UTC, closed without merging