Added Custom Themes Support And Settings Modal
danny-avila/LibreChat pull request #238
Opened 2023-05-11 10:41 UTC by techwithanirudh

2023-05-11 13:27 UTC, danny-avila requested changes

2023-05-11 13:27 UTC, danny-avila commented on client/public/assets/favicon-32x32.png
Is this necessary?

2023-05-11 13:27 UTC, danny-avila commented on api/server/routes/endpoints.js
Many files are changed with small formatting issues. I believe you’re not adhering to the eslint config and maybe using your own linter rules

2023-05-11 13:27 UTC, danny-avila commented on .replit
Is this necessary? Should this be gitignored?

2023-05-11 13:27 UTC, danny-avila commented on client/src/style.css
There is no way I can approve this PR with so many changes to the main style sheet and not enough support as to why

2023-05-11 13:28 UTC, techwithanirudh commented on client/public/assets/favicon-32x32.png
No...

2023-05-11 13:38 UTC, techwithanirudh commented on api/server/routes/endpoints.js
Sorry, I will relint it

2023-05-11 16:06 UTC, danny-avila commented
I appreciate your recent efforts in contributing to our project with this PR. The time and dedication you've put into it is valued. However, after careful consideration, it became clear that the scope and depth of this Pull Request warrant revisiting our approach to new features.

Given the scope-creep we're noticing in the project, we are adopting a deeper strategy/process for proposing new features. This is driven by our aim to prevent:

    Rejecting PRs, causing contributors to feel frustrated and undervalued.
    Managing chaos arising from conflicting priorities that disrupt ongoing tasks in various areas of the project.
    Accepting code that does not align with our architectural and design direction, leading to refactoring and maintenance burdens.

As a part of this new process, we're introducing a proposal outline for feature requests. This should cover aspects such as the description of changes, the intention behind them, the necessity of the feature, affected areas of the application, designs if relevant to UI, and so on. We believe this will streamline our collaborative efforts by fostering discussions and iterations on-feature proposals before any actual work begins.

In light of our new standards and goals, we are unable to accept your current PR. We noticed that there were 45 files changed with many personal linting rules ignoring the eslint config in our repo. Moreover, the main stylesheet had 1500 lines removed, and there were .replit code and personal shell scripts included that are not typically utilized. Additionally, please note that we are transitioning our client code to TypeScript. Therefore, any incoming JavaScript code would increase the workload on our team.

We encourage you to consider the new proposal outline process and starting a discussion in the github discussions section after seeking alignment with our strategic direction. This will help ensure that we create high-quality and coherent outputs that bring value to our project and maintain long-term project health. 

Right now, we are more likely to approve PRs for actions on our trello, which we will transition to the GitHub projects section, and PRs smaller in scope.

We truly appreciate your understanding as we work together to build a strong project foundation moving forward. Please do not hesitate to reach out if you have any questions or need further clarification on the new process.

Kind regards,

2023-05-11 16:06 UTC, closed without merging

2023-05-12 08:05 UTC, techwithanirudh commented on client/src/style.css
All of the css in the main stylesheet were not required as tailwind will handle all of the css. Some values were hard coded in the css which broke themes support. As such the majority of the css was removed

2023-05-12 08:16 UTC, techwithanirudh commented on api/server/routes/endpoints.js
Relinted it

2023-05-12 08:16 UTC, techwithanirudh commented on client/public/assets/favicon-32x32.png
Resolved in latest commit

2023-05-12 08:16 UTC, techwithanirudh commented on api/server/routes/endpoints.js
Resolved in latest commit

2023-05-12 08:16 UTC, techwithanirudh commented on .replit
Resolved in latest commit

2023-05-12 08:17 UTC, techwithanirudh commented on client/src/style.css
Resolved in latest commit