feat: Minor UI Design Changes
danny-avila/LibreChat pull request #2619
Opened 2024-05-05 07:12 UTC by techwithanirudh

# Pull Request Template

### ⚠️ Before Submitting a PR, read the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) in full!

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] New documents have been locally validated with mkdocs

2024-05-08 20:41 UTC, danny-avila commented
There's 2 minor merge conflicts, I will see if I can resolve them later unless you beat me to it.

2024-05-09 11:17 UTC, techwithanirudh commented
@danny-avila I resolved the merge conflicts 😉

2024-05-09 17:30 UTC, danny-avila commented
A lot of changes here that could've been individual PRs. Please reduce the scope of your PRs next time.

2024-05-09 17:36 UTC, danny-avila requested changes

2024-05-09 17:36 UTC, danny-avila commented on client/src/components/Chat/Header.tsx
> +      <div className="hide-scrollbar flex w-full items-center justify-between gap-2 overflow-x-auto">
Refactor the export functions into its own component, please.

2024-05-09 17:40 UTC, danny-avila commented on client/src/components/Chat/Header.tsx
> +      <div className="hide-scrollbar flex w-full items-center justify-between gap-2 overflow-x-auto">
this change should only add 2lines to `client/src/components/Chat/Header.tsx`

2024-05-09 21:12 UTC, danny-avila approved these changes

2024-05-09 21:46 UTC, merged