🔧 fix: Convo fade effect
danny-avila/LibreChat pull request #2642
Opened 2024-05-08 22:19 UTC by walbercardoso

Fix  Convo fade effect

Before:

![image](https://github.com/danny-avila/LibreChat/assets/50842245/5a77115f-281c-4d84-b875-2e5ca94658fe)

After:
![image](https://github.com/danny-avila/LibreChat/assets/50842245/87f06136-5772-4fe8-a465-6d1c7dcca279)

Mouse Over:

Before:
![image](https://github.com/danny-avila/LibreChat/assets/50842245/3eca1cb0-8cfb-4d1f-9ee6-6bf9f03dd888)

After:
![image](https://github.com/danny-avila/LibreChat/assets/50842245/52c42db4-b30e-4241-8107-035d77a8e070)

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

Please delete any irrelevant options.

- [X] My code adheres to this project's style guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented in any complex areas of my code
- [X] I have made pertinent documentation changes
- [X] My changes do not introduce new warnings
- [X] I have written tests demonstrating that my changes are effective or that my feature works
- [X] Local unit tests pass with my changes
- [X] Any changes dependent on mine have been merged and published in downstream modules.
- [X] New documents have been locally validated with mkdocs

2024-05-08 22:40 UTC, danny-avila requested changes
thanks again, I haven't tested the first comment but would be nice to remove the additional state and listeners.

2024-05-08 22:40 UTC, danny-avila commented on client/src/components/Conversations/Convo.tsx
> +              isHovering ? 'from-60%' : 'from-0%'
Thanks for the PR @walbercardoso 

is the listener necessary? because this should be the equivalent of 

`group-hover:from-60% from-0%`

2024-05-08 22:40 UTC, danny-avila commented on client/src/components/Conversations/HoverToggle.tsx
> +          'teom-gray-500 peer absolute bottom-0 right-0 top-0 items-center gap-1.5 rounded-r-lg from-gray-900 pl-2 pr-2 dark:text-white',
typo? `teom`

2024-05-09 00:49 UTC, walbercardoso commented on client/src/components/Conversations/HoverToggle.tsx
> +          'teom-gray-500 peer absolute bottom-0 right-0 top-0 items-center gap-1.5 rounded-r-lg from-gray-900 pl-2 pr-2 dark:text-white',
Hi @danny-avila .. still working on it. Just a few more minutes and i will update it

2024-05-09 00:59 UTC, walbercardoso commented
I think now is good to go.

2024-05-09 01:21 UTC, merged