Updating Messages feature with files from new/feat/new-ui
danny-avila/LibreChat pull request #2741
Opened 2024-05-16 06:36 UTC by techwithanirudh

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

⚠️ This P.R is generated by GPT-4o.

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

2024-05-20 07:27 UTC, techwithanirudh commented
@danny-avila Could you please review this P.R?

2024-05-20 20:01 UTC, berry-13 commented
@techwithanirudh many of my friends don't want to use the new "Chat bubble". Could we create a switch for it? additionally, can we include this "var" in the "edit messages" PR?

2024-05-21 08:00 UTC, techwithanirudh commented
> @techwithanirudh many of my friends don't want to use the new "Chat bubble". Could we create a switch for it? additionally, can we include this "var" in the "edit messages" PR?

Once this pull request is merged, I will add the conditional check for the parameter in the EditMessages pull request, but other than that everything is done.

2024-05-21 13:50 UTC, berry-13 commented
> > @techwithanirudh many of my friends don't want to use the new "Chat bubble". Could we create a switch for it? additionally, can we include this "var" in the "edit messages" PR?
> 
> Once this pull request is merged, I will add the conditional check for the parameter in the EditMessages pull request, but other than that everything is done.

thanks!

2024-05-27 16:52 UTC, danny-avila commented
> > @techwithanirudh many of my friends don't want to use the new "Chat bubble". Could we create a switch for it? additionally, can we include this "var" in the "edit messages" PR?
> 
> Once this pull request is merged, I will add the conditional check for the parameter in the EditMessages pull request, but other than that everything is done.



> > @techwithanirudh many of my friends don't want to use the new "Chat bubble". Could we create a switch for it? additionally, can we include this "var" in the "edit messages" PR?
> 
> Once this pull request is merged, I will add the conditional check for the parameter in the EditMessages pull request, but other than that everything is done.



> > @techwithanirudh many of my friends don't want to use the new "Chat bubble". Could we create a switch for it? additionally, can we include this "var" in the "edit messages" PR?
> 
> Once this pull request is merged, I will add the conditional check for the parameter in the EditMessages pull request, but other than that everything is done.

I won't be merging this PR unless there is a way to select different themes for the new UI updates, with the current theme being the default.

2024-05-28 13:34 UTC, techwithanirudh commented
@danny-avila This has already been implemented in this P.R

2024-06-01 16:54 UTC, danny-avila commented
> @danny-avila This has already been implemented in this P.R, if this P.R gets merged I could update the others to do the same.

Ok, I didn't realize that. I will try it out.

2024-06-06 06:13 UTC, techwithanirudh commented
> > @danny-avila This has already been implemented in this P.R, if this P.R gets merged I could update the others to do the same.
> 
> Ok, I didn't realize that. I will try it out.

@danny-avila Thanks! I'll resolve the merge conflicts

2024-06-08 22:30 UTC, danny-avila requested changes

2024-06-08 22:30 UTC, danny-avila commented on client/src/store/settings.ts
> +  messagesUI: atomWithLocalStorage('messagesUI', true),
default value should be `false`

2024-06-08 22:30 UTC, danny-avila commented on client/src/localization/languages/Eng.ts
> +  com_nav_messages_ui: 'Enable new UI',
"Use Bubble styling for User Messages"

2024-06-08 22:30 UTC, danny-avila commented on client/src/components/Nav/SettingsTabs/General/General.tsx
> +        <div className="border-b pb-3 last-of-type:border-b-0 dark:border-gray-600">
This should go in a new Tab called "Appearance"

2024-06-08 22:36 UTC, danny-avila commented
The hover buttons should also hover when the entire message row is being hovered in the new style. currently it does not, and it doesn't feel intuitive to hover over the bubble first.


https://github.com/danny-avila/LibreChat/assets/110412045/52b0ac5f-9f86-45e3-a215-9ca2f2e66728

2024-06-09 04:39 UTC, techwithanirudh commented
> The hover buttons should also hover when the entire message row is being hovered in the new style. currently it does not, and it doesn't feel intuitive to hover over the bubble first.
> 
>  Recording.2024-06-08.183608.mp4

@danny-avila I tried to fix this issue, is this fix okay?

2024-06-25 05:38 UTC, closed without merging

2024-06-25 07:07 UTC, danny-avila commented
This PR was closed due to fundamental changes made to messages to accommodate this PR https://github.com/danny-avila/LibreChat/pull/3191

I'm still open to the bubble message look as an option but with geared for dependency injection from the start, with minimal code edits to the main message components and Hover buttons.

I closed this PR as I don't expect the changes to be reconciled from the current state of the PR which already had some merge conflicts before #3191