🎤 feat: add custom speech config, browser TTS/STT features, and dynamic speech tab settings
danny-avila/LibreChat pull request #2921
Opened 2024-05-30 15:55 UTC by berry-13

## Summary

- Added custom speech configuration in `librechat.yaml`. This allows the ADMIN to set pre-configured "speech tab" settings
- feat: Browser TTS language selection
- feat: Browser STT streaming
- fix: Speech tab settings dynamically appear and disappear based on user settings (i.e. browser/external engine dropdown)
- refactor: `endpointSTT` and `endpointTTS` renamed to `engineSTT` and `engineTTS`

### BREAKING: `SpeechToText` and `TextToSpeech` store's variables were renamed to `speechToText` and `textToSpeech`. If you're having any issues, delete librechat's cache

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

**external stt/tts:** ElevenLabs and OpenAI

**local stt/tts:** Chrome

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] A pull request for updating the documentation has been submitted.

2024-05-30 16:08 UTC, danny-avila requested changes

2024-05-30 16:08 UTC, danny-avila commented on api/server/routes/files/index.js
> +  router.use('/speech', speech);
update your branch and you'll see an important note on route initialization order

2024-05-30 16:08 UTC, danny-avila commented on client/src/hooks/Input/useSpeechToTextBrowser.ts
> +      if (!isMicrophoneAvailable) {
`if (!browserSupportsSpeechRecognition) {`

early return instead of nesting

2024-05-30 16:08 UTC, danny-avila commented on client/src/hooks/Input/useSpeechToTextBrowser.ts
> +      if (e.shiftKey && e.altKey && e.code === 'KeyL' && !useExternalSpeechToText) {
is `useExternalSpeechToText` a hook or a boolean value? you should not name a variable starting with `use` in react unless it's a hook

2024-05-30 16:08 UTC, danny-avila commented on client/src/hooks/Input/useSpeechToTextBrowser.ts
> +    isListening: isListening,
redundant

2024-06-12 13:51 UTC, danny-avila commented
please fix the broken test

2024-06-15 13:36 UTC, danny-avila commented
slated for v0.7.4

2024-06-21 13:35 UTC, danny-avila commented
Hi Berry, there are elevated errors when using this without config settings

```yaml
memory, and will not scale past a single process.
2024-06-21 09:31:55 info: Server listening on all interfaces at port 3080. Use http://localhost:3080 to access it
2024-06-21 09:31:59 error: Failed to get speechTab settings: Configuration or speechTab schema is missing
2024-06-21 09:31:59 error: Failed to get voices: Configuration or TTS schema is missing
2024-06-21 09:32:45 error: Failed to get speechTab settings: Configuration or speechTab schema is missing
2024-06-21 09:32:45 error: Failed to get voices: Configuration or TTS schema is missing
```

I should not be seeing any errors when I don't have speech enabled/configured and I open the Settings

2024-06-21 13:38 UTC, danny-avila commented
Also when i add the new format for speech settings, i should not get an error if i don't have speechTab settings
```bash
2024-06-21 09:36:42 error: Failed to get speechTab settings: Configuration or speechTab schema is missing
```

2024-06-21 13:42 UTC, danny-avila commented
lastly, if I'm using the old setup, this error message is confusing and I will think the app has a bug:
```bash
2024-06-21 09:40:49 error: Invalid custom config file at /home/danny/LibreChat/librechat.yaml [
  {
    "code": "unrecognized_keys",
    "keys": [
      "tts",
      "stt"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'tts', 'stt'"
  }
]
```

this is a parsing error for the custom config file, we should still show it, but also add a note if this error message is detected, that the format has changed.

Also please accompany this PR with an update to the changelog: https://www.librechat.ai/changelog

2024-07-05 13:51 UTC, danny-avila commented
> lastly, if I'm using the old setup, this error message is confusing and I will think the app has a bug:
> 
> ```shell
> 2024-06-21 09:40:49 error: Invalid custom config file at /home/danny/LibreChat/librechat.yaml [
>   {
>     "code": "unrecognized_keys",
>     "keys": [
>       "tts",
>       "stt"
>     ],
>     "path": [],
>     "message": "Unrecognized key(s) in object: 'tts', 'stt'"
>   }
> ]
> ```
> 
> this is a parsing error for the custom config file, we should still show it, but also add a note if this error message is detected, that the format has changed.
> 
> Also please accompany this PR with an update to the changelog: https://www.librechat.ai/changelog

@berry-13 this is what I meant: https://github.com/danny-avila/LibreChat/pull/2921/commits/51c5d0488a155b773e8692efcc630569371f7dfe

2024-07-05 14:11 UTC, berry-13 commented
> @berry-13 this is what I meant: [51c5d04](https://github.com/danny-avila/LibreChat/commit/51c5d0488a155b773e8692efcc630569371f7dfe)

oh ok, sorry. I was thinking about every key, not just `stt` and `tts`

2024-07-05 14:13 UTC, danny-avila approved these changes

2024-07-05 14:13 UTC, merged

2024-07-05 20:04 UTC, dkindlund commented
Hey @danny-avila and @berry-13 -- I was trying to get the `whisper-1` model to work with `stt` using the `LiteLLM` proxy.

My `librechat.yaml` looks like:
```
speech:
  stt:
    openai:
      url: 'https://litellmproxy/v1/audio/transcriptions'
      apiKey: 'sk-1234'
      model: 'whisper-1'
 ```
 
 When I try using external STT, I get an error in the client and these are the messages I'm seeing in the server logs:
 ```
 An error occurred while preparing the OpenAI API STT request:  Cannot read properties of undefined (reading 'openai')
 An error occurred while processing the audio: Cannot read properties of undefined (reading 'status')
 ```
 
 Is there something else I'm missing to make STT work in LibreChat?  Thanks!