🗣️ feat: Azure OpenAI speech
danny-avila/LibreChat pull request #2985
Opened 2024-06-06 22:38 UTC by berry-13

## Summary

fixed Azure OpenAI STT and added Azure OpenAI TTS

## Change Type

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] A pull request for updating the documentation has been submitted.

2024-06-15 13:36 UTC, danny-avila commented
slated for v0.7.4

2024-06-21 13:48 UTC, danny-avila requested changes
Also, can you raise updated docs for librechat.ai with this change?

2024-06-21 13:48 UTC, danny-avila commented on api/server/services/Files/Audio/textToSpeech.js
> +    case 'azureOpenAI':
can you use enums for this?

2024-06-21 13:48 UTC, danny-avila commented on api/server/services/Files/Audio/getVoices.js
> +      case 'azureOpenAI':
enums

2024-07-01 07:51 UTC, berry-13 commented
> Also, can you raise updated docs for librechat.ai with this change?

the docs are in the same [PR](https://github.com/LibreChat-AI/librechat.ai/pull/61) of #2921

2024-07-05 14:14 UTC, danny-avila commented
@berry-13 please resolve the merge conflicts (result of #2921)

2024-07-09 19:23 UTC, danny-avila approved these changes

2024-07-10 20:33 UTC, merged