Turkish language update
danny-avila/LibreChat pull request #3232
Opened 2024-06-29 09:08 UTC by eniyiweb

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

2024-06-30 17:55 UTC, danny-avila commented
Thank you for this. Please resolve the merge conflicts. Also it's not necessary to modify the bottom portion of the language file, you should not remove it either.

2024-06-30 17:56 UTC, danny-avila requested changes

2024-06-30 17:56 UTC, danny-avila commented on client/src/localization/languages/Tr.ts
> -export const comparisons = {
this should be left untouched

2024-07-02 14:52 UTC, eniyiweb commented on client/src/localization/languages/Tr.ts
> -export const comparisons = {
Ok, I fixed it

2024-07-09 12:30 UTC, danny-avila approved these changes

2024-07-09 12:30 UTC, merged