Tooltip to inform of reason for disabled action
danny-avila/LibreChat pull request #3239
Opened 2024-06-30 17:45 UTC by CakeCrusher

## Note
I added the following TODOs:
- `{/* TODO: incorporate localize */}` I did not incorporate the translations for this tooltip message
- `{/* TODO: refactor to use https://atomiks.github.io/tippyjs/ */}` Using this custom tooltip UI is convoluted tippyjs could significantly simplify this.
## Summary
when creating an action for an assistant the button is sometimes disabled if the assistant has not yet been created therefore without an explanation of why it's disabled this PR informs the user of why the button is disabled.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing
you click on assistance and then you go to assistant builder where you will see that for an assistant that is already created the action button is activated but if you try and create a new action the action button defaults to disabled that is when the tooltip shows why it is disabled.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes

2024-06-30 17:46 UTC, CakeCrusher commented
@danny-avila

2024-06-30 17:52 UTC, danny-avila requested changes

2024-06-30 17:52 UTC, danny-avila commented on client/src/components/SidePanel/Builder/AssistantPanel.tsx
> +                    {/* TODO: refactor to use https://atomiks.github.io/tippyjs/ */}
?

2024-06-30 17:52 UTC, danny-avila commented on client/src/components/SidePanel/Builder/AssistantPanel.tsx
> +                            {/* TODO: incorporate localize */}
yes, please incorporate it

2024-06-30 17:54 UTC, danny-avila commented on client/src/components/SidePanel/Builder/AssistantPanel.tsx
> +                    {/* TODO: refactor to use https://atomiks.github.io/tippyjs/ */}
No thank you on `tippyjs`

2024-10-02 07:47 UTC, CakeCrusher commented
Moved to #4306

2024-10-02 07:47 UTC, closed without merging