Update ldapStrategy.js
danny-avila/LibreChat pull request #3247
Opened 2024-07-02 06:03 UTC by ravi-katiyar

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

2024-07-04 09:54 UTC, berry-13 requested changes

2024-07-04 09:54 UTC, berry-13 commented on api/strategies/ldapStrategy.js
> +const rejectUnauthorized = LDAP_TLS_REJECT_UNAUTHORIZED !== 'false';
can you please use
```
const { isEnabled } = require('~/server/utils');
```

2024-07-04 11:15 UTC, ravi-katiyar commented on api/strategies/ldapStrategy.js
> +const rejectUnauthorized = LDAP_TLS_REJECT_UNAUTHORIZED !== 'false';
Does it look ok now ?

2024-07-04 13:18 UTC, berry-13 commented on api/strategies/ldapStrategy.js
> +const rejectUnauthorized = LDAP_TLS_REJECT_UNAUTHORIZED !== 'false';
yes, thanks

2024-07-04 13:20 UTC, berry-13 approved these changes

2024-07-08 09:29 UTC, ravi-katiyar commented
@danny-avila please let me know if anything is pending at my end for this.

2024-07-09 17:34 UTC, ravi-katiyar commented
@berry-13 please let me if there's anything pending on this , I would like to get this merged.

2024-07-10 20:36 UTC, danny-avila commented
@ravi-katiyar can you add relevent documentation to

https://www.librechat.ai/docs/configuration/authentication/ldap ?

https://github.com/LibreChat-AI/librechat.ai/blob/main/pages/docs/configuration/authentication/ldap.mdx ?


Since you area also adding an .env variable, you should update this too: https://github.com/LibreChat-AI/librechat.ai/blob/main/pages/docs/configuration/dotenv.mdx

2024-07-11 18:55 UTC, ravi-katiyar commented
> @ravi-katiyar can you add relevent documentation to
> 
> https://www.librechat.ai/docs/configuration/authentication/ldap ?
> 
> https://github.com/LibreChat-AI/librechat.ai/blob/main/pages/docs/configuration/authentication/ldap.mdx ?
> 
> Since you area also adding an .env variable, you should update this too: https://github.com/LibreChat-AI/librechat.ai/blob/main/pages/docs/configuration/dotenv.mdx

@danny-avila , Thanks for pointing that out. PR submitted to update the docs https://github.com/LibreChat-AI/librechat.ai/pull/89

2024-07-27 19:44 UTC, danny-avila approved these changes

2024-07-27 19:46 UTC, merged