feat/Modal Terms and Conditions Dialog
danny-avila/LibreChat pull request #3712
Opened 2024-08-20 12:09 UTC by maxesse

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

This feature provides a modal terms and conditions acceptance dialogue that the user needs to accept to proceed.
It's set up by the user by adding three options to librechat.yaml. modalAcceptance enables the feature, modalTitle assigns a custom title to it (if empty, a standard localised string will be used for Terms of Service), and modalContent (if empty the dialogue will say that there is no content). The content is expected to be presented in markdown. This is because embedding HTML led to... mixed results depending on what was coming in. The standard externalUrl parameters is still being used for LibreChat's terms of use link on the footer.

The change also provides a npm script (`npm run reset-terms`) to set all users to a non-accepted status (useful in case the terms and conditions change and need to be accepted again).

The change has been localised for all supported LibreChat languages too, except the content of the terms, as that would force users to change files under source control. Besides, it's quite common for terms and conditions to be in the native language of the country in which the instance is deployed, even if the rest is localised.

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Translation update

## Testing

I tested the feature with each of the options with values and not to ensure that it doesn't break anything.

### **Test Configuration**:

Add the following to librechat.yaml:

```
  # Terms of service
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true
    modalAcceptance: true
    modalTitle: "Terms of Service for LibreChat"
    modalContent: |
      # Terms and Conditions for LibreChat

      *Effective Date: February 18, 2024*

      Welcome to LibreChat, the informational website for the open-source AI chat platform, available at https://librechat.ai. These Terms of Service ("Terms") govern your use of our website and the services we offer. By accessing or using the Website, you agree to be bound by these Terms and our Privacy Policy, accessible at https://librechat.ai//privacy.
```

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [ ] A pull request for updating the documentation has been submitted.

2024-08-20 12:38 UTC, berry-13 requested changes
I hope that all my comments make sense, thanks!

@danny-avila should we still access directly the User model?

2024-08-20 12:38 UTC, berry-13 commented on client/src/components/ui/TermsAndConditionsModal.tsx
> +import { Dialog } from '~/components/ui';
use OGDialog instead of Dialog

2024-08-20 12:38 UTC, berry-13 commented on api/server/controllers/UserController.js
> +const User = require('~/models/User'); // Add this line
remove this comment

2024-08-20 12:38 UTC, berry-13 commented on api/server/controllers/UserController.js
> +    console.error('Error fetching terms acceptance status:', error);
instead of `console`, use `logger`
```
const { logger } = require('~/config');
```

2024-08-20 12:38 UTC, berry-13 commented on client/src/components/ui/TermsAndConditionsModal.tsx
> +      const response = await fetch('/api/user/terms/accept', {
don't make raw requests, use react query (in `data-provider`). This apply for both the post and get request

2024-08-20 12:38 UTC, berry-13 commented on client/src/components/ui/TermsAndConditionsModal.tsx
> +        console.error('Failed to accept terms:', errorData.message);
if you want, show a toast but don't console log
```ts
import { useToastContext } from '~/Providers';
const { showToast } = useToastContext();
 ```

2024-08-20 12:38 UTC, berry-13 commented on client/src/routes/Root.tsx
> +      fetch('/api/user/terms', {
don't make raw requests, use react query (in data-provider). This apply for both the post and get request

2024-08-20 12:38 UTC, berry-13 commented on client/src/routes/Root.tsx
> +          console.error('Error fetching terms acceptance status:', error);
use showToast

2024-08-20 12:38 UTC, berry-13 commented on client/src/components/ui/TermsAndConditionsModal.tsx
> +      />
don't use legacy `-gray-`, instead use `bg-surface-*` and `border-border-*`

2024-08-20 12:38 UTC, berry-13 commented on package-lock.json
revert back the changes you made on this package-lock

2024-08-20 22:51 UTC, danny-avila commented
> @danny-avila should we still access directly the User model?

No, thanks for catching that!

And @maxesse thanks so much for the PR

2024-08-21 12:20 UTC, berry-13 commented
@maxesse Thank you! Could you reset the package lock? The easiest way is to just copy the package-lock from our repo to yours and make a commit; this way, you’re aligned with ours. Otherwise, you could try using `npm run reinstall`

2024-08-21 13:22 UTC, maxesse commented
Hello @berry-13, I just repushed package-lock copying it from librechat/main (I had done it yesterday, but for some reason it must have changed again?!).
Also, I am getting some warnings about peer dependencies since a few days ago when running npm update.

librechatadm@LibrechatVMNPMDev:~/LibreChat$ npm update
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @langchain/community@0.0.46
npm warn Found: mongodb@4.17.2
npm warn node_modules/mongodb
npm warn   mongodb@"^4.5.0" from @keyv/mongo@2.2.8
npm warn   node_modules/@keyv/mongo
npm warn     @keyv/mongo@"^2.1.8" from @librechat/backend@0.7.4
npm warn     api
npm warn
npm warn Could not resolve dependency:
npm warn peerOptional mongodb@"^5.2.0" from langchain@0.0.214
npm warn node_modules/langchain
npm warn   langchain@"^0.0.214" from @librechat/backend@0.7.4
npm warn   api
npm warn   1 more (langsmith)

2024-08-22 08:02 UTC, maxesse commented
Hello, @danny-avila @berry-13 do you need me to do anything else on this PR?

2024-08-26 16:41 UTC, danny-avila commented
Hi @maxesse 

Please resolve the conflicts, I will try to review this during the week since there's a lot of changes.

I'm cutting a release candidate today, merging this in at some point after that makes sense.

2024-08-26 16:43 UTC, maxesse commented
Ok @danny-avila, I'm travelling for work today and tomorrow, will merge with main on Wednesday and solve the conflicts 👍🏻

2024-08-26 17:46 UTC, danny-avila commented
> Ok @danny-avila, I'm travelling for work today and tomorrow, will merge with main on Wednesday and solve the conflicts 👍🏻

sweet!

2024-08-27 11:58 UTC, maxesse commented
@danny-avila ok, I solved the conflict (was only a very small thing in api-endpoints at the end of the file). Also there's a separate PR on the librechat.ai repo for the docs update.

2024-08-31 20:07 UTC, danny-avila approved these changes

2024-08-31 20:08 UTC, merged