Update message design
danny-avila/LibreChat pull request #4044
Opened 2024-09-13 20:21 UTC by machinsoft

I made the design somewhat similar to OpenAI for messages.

Before

![image](https://github.com/user-attachments/assets/ea1e61e5-e173-4e30-9bba-d83f63df08c2)
![image](https://github.com/user-attachments/assets/d5aeb2fd-0bf0-443f-b0f8-2d53184bde3c)
![image](https://github.com/user-attachments/assets/61c5c01d-7a5e-4aa2-a529-e87d7818e199)
![image](https://github.com/user-attachments/assets/b0c29b8f-bd3b-4a98-a3a4-6936eaafe3f6)

After

![image](https://github.com/user-attachments/assets/1a483654-afc2-4b6d-bea6-a66e19a27cac)
![image](https://github.com/user-attachments/assets/cb13d105-bb2f-45d3-a700-aa4e51cf7ae6)
![image](https://github.com/user-attachments/assets/f6b394ab-9616-4af3-a4a2-9ced87db130e)
![image](https://github.com/user-attachments/assets/610fdec2-9789-4aed-844d-13c2ff8bd96f)

2024-09-14 17:01 UTC, danny-avila commented
make this an option from YAML and/or settings dialog instead of the default, then I will merge it

2024-09-14 17:03 UTC, danny-avila requested changes

2024-09-14 17:03 UTC, danny-avila commented on client/src/components/Chat/Messages/HoverButtons.tsx
> +            'hover-button rounded-md p-1 hover:bg-gray-100 hover:text-gray-500 focus:opacity-100 dark:text-gray-400/70 dark:hover:bg-gray-700 dark:hover:text-gray-200 disabled:dark:hover:text-gray-40
use our new theming classes, e.g. `bg-surface-primary`, `bg-surface-secondary`, etc.

Do a CTRL+F for `gray-700` and it should be the first hit in styles.css:


```css
/* Custom Variables */
:root {
  --white: #fff;
  --black: #000;
  --gray-20: #ececf1;
  --gray-50: #f7f7f8;
  --gray-100: #ececec;
  --gray-200: #e3e3e3;
  --gray-300: #cdcdcd;
  --gray-400: #999696;
  --gray-500: #595959;
  --gray-600: #424242;
  --gray-700: #2f2f2f;
  --gray-800: #212121;
  --gray-850: #171717;
  --gray-900: #0d0d0d;
  --gizmo-gray-500: #999;
  --gizmo-gray-600: #666;
  --gizmo-gray-950: #0f0f0f;
  --font-size-xs: 0.75rem;
  --font-size-sm: 0.875rem;
  --font-size-base: 1rem;
  --font-size-lg: 1.125rem;
  --font-size-xl: 1.25rem;
}
html {
  --text-primary: var(--gray-800);
  --text-secondary: var(--gray-600);
  --text-secondary-alt: var(--gray-500);
  --text-tertiary: var(--gray-500);
  --ring-primary: var(--gray-500);
  --header-primary: var(--white);
  --header-hover: var(--gray-50);
  --header-button-hover: var(--gray-50);
  --surface-active: var(--gray-100);
  --surface-hover: var(--gray-200);
  --surface-primary: var(--white);
  --surface-primary-alt: var(--gray-50);
  --surface-primary-contrast: var(--gray-100);
  --surface-secondary: var(--gray-50);
  --surface-tertiary: var(--gray-100);
  --surface-tertiary-alt: var(--white);
  --border-light: var(--gray-200);
  --border-medium-alt: var(--gray-300);
  --border-medium: var(--gray-300);
  --border-heavy: var(--gray-400);
  --border-xheavy: var(--gray-500);
}
.dark {
  --text-primary: var(--gray-100);
  --text-secondary: var(--gray-300);
  --text-secondary-alt: var(--gray-400);
  --text-tertiary: var(--gray-500);
  --header-primary: var(--gray-700);
  --header-hover: var(--gray-600);
  --header-button-hover: var(--gray-700);
  --surface-active: var(--gray-500);
  --surface-hover: var(--gray-600);
  --surface-primary: var(--gray-900);
  --surface-primary-alt: var(--gray-850);
  --surface-primary-contrast: var(--gray-850);
  --surface-secondary: var(--gray-800);
  --surface-tertiary: var(--gray-700);
  --surface-tertiary-alt: var(--gray-700);
  --border-light: var(--gray-700);
  --border-medium-alt: var(--gray-600);
  --border-medium: var(--gray-600);
  --border-heavy: var(--gray-500);
  --border-xheavy: var(--gray-400);
}
```

2024-09-14 17:33 UTC, apxgpt commented on client/src/components/Chat/Messages/HoverButtons.tsx
> +            'hover-button rounded-md p-1 hover:bg-gray-100 hover:text-gray-500 focus:opacity-100 dark:text-gray-400/70 dark:hover:bg-gray-700 dark:hover:text-gray-200 disabled:dark:hover:text-gray-40
I'm having a hard time understanding exactly what needs to be done. However, if you could show me an example of what needs to be changed, I think I'll be able to grasp it better.

2024-09-14 21:21 UTC, danny-avila commented
> Personally, I think it's better not to get stuck with the old interface but to stick with the OpenAI design, as that's what we initially aimed for. If we create a bulky settings interface, people won't use it anyway—most users stick to the defaults and don't dig into settings. 

I disagree, as I prefer the current design. There is no obligation to adhere to OpenAI here. I understand that some may prefer this, so that's why I'm pushing for an option. 

> I understand what you're asking for, but it's a bit difficult for me to implement because I haven't done something like this before. I'm not familiar with making features configurable through YAML or a settings dialog. ... For example, the "Display username in messages" setting doesn't make much sense and can simply be deleted.

You should learn from the example you gave

2024-09-15 16:38 UTC, berry-13 commented
@machinsoft don't close this. I can work on it

2024-09-17 17:03 UTC, techwithanirudh commented
I worked on this a while back, it might help with adding a toggle to the messages ui.

2025-04-09 14:07 UTC, closed without merging