Add feature to dynamically pass the email address of users to HTTP headers of custom endpoints
danny-avila/LibreChat pull request #4488
Opened 2024-10-21 16:13 UTC by timmanik

## Summary

I encountered a use cases that needed me to pass the user email address to the HTTP header of my endpoint. My endpoint is a custom endpoint: [Portkey](https://github.com/Portkey-AI/gateway), an LLM Gateway. Porktey requires email addresses or unique identifiers of users be sent through [HTTP headers](https://portkey.ai/docs/api-reference/inference-api/headers#2-metadata-x-portkey-metadata) so that each user's request/usage can be tracked granularly.

Given this need, I modified the way that LibreChat passes its header to custom endpoints (like Portkey) via the `initialize.js` for custom endpoints.

The updated code block iterates over the headers in **endpointConfig**, and for each header that contains the **${USER_EMAIL}** placeholder, it replaces it with the corresponding user's email fetched from the database.

For headers without **${USER_EMAIL}**, it resolves any other environment variables using extractEnvVariable, and handles errors by assigning 'null' as a fallback.

More info on the use case can be found [here](https://github.com/timmanik/librechat-for-portkey).

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

2025-02-24 16:11 UTC, rubentalstra commented
@timmanik please fix the eslint issues^

2025-06-16 15:59 UTC, timmanik commented
@rubentalstra there were some merge conflicts when you tried to merge the PR. I fixed them. Please let me know if anything else is needed.

2025-06-16 16:09 UTC, danny-avila requested changes

2025-06-16 16:09 UTC, danny-avila commented on api/server/services/Endpoints/custom/initialize.js
> +const resolveUserEmail = async (value, userId) => {
Please look into how user info fields are resolved for MCP Server Configuration, which you should match:
https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/mcp_servers#headers

The main function concerning this feature is [`processMCPEnv`](https://github.com/danny-avila/LibreChat/blob/0103b4b08a6ee1339569d7d4af16beaaac0228ed/packages/data-provider/src/mcp.ts#L176)

Please look into its usage and adapt it correctly here.

Also, please start a new PR with only unique commits, only including new changes, and not merge artifacts

2025-06-16 16:13 UTC, timmanik commented on api/server/services/Endpoints/custom/initialize.js
> +const resolveUserEmail = async (value, userId) => {
Thanks for the suggestions -- I'll work on those. Will close this PR and start a new one.

2025-06-16 16:15 UTC, timmanik commented
Closing this PR to create a new clean one to include only new changes and not merged artifacts.

2025-06-16 16:15 UTC, closed without merging