feat: google workspace limit access to a single group
danny-avila/LibreChat pull request #4613
Opened 2024-11-02 13:02 UTC by owengo

# Pull Request Template
⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)
https://github.com/LibreChat-AI/librechat.ai/pull/159

## Summary

https://github.com/danny-avila/LibreChat/discussions/1746
When google login is configured for a workspace account the feature permits to restricts logins to members of a group.

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

- If the GOOGLE_WORKSPACE_GROUP is not defined in the .env,or if it's empty, nothing changes: all members of the workspace account can login and no extra scopes are required in the oauth2 consent screen.
- When GOOGLE_WORKSPACE_GROUP is set:
  - all oauth2 consent screen require the extra 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'  scope permission aka: "See any Cloud Identity Groups that you can access, including group members and their emails"
  - at login, if the user:
    - is allowed to list the members of the configured group
    - is member of the configured group
      - access is granted normally
    - else
      - access is refused and user is redirected to the login page at the end of oauth process

### **Test Configuration**:

The feature works with google workspaces accounts. A group must be created in the workspace account and member of the group must be allowed to see the members of the group.
The email address of the group has to be configured in the .env as GOOGLE_WORKSPACE_GROUP=<email address of the group>
Note that the group can contain other groups and all member of the included groups will also be allowed.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] A pull request for updating the documentation has been submitted.

2025-02-24 16:22 UTC, rubentalstra requested changes
thank you for doing this manual. but would it be possible to use the google's official `npm` package

https://googleapis.dev/nodejs/googleapis/latest/cloudidentity/classes/Cloudidentity.html
https://www.npmjs.com/package/@googleapis/cloudidentity

2025-02-24 16:22 UTC, rubentalstra commented on api/strategies/googleStrategy.js
> +}
thank you for doing this manual. but would it be possible to use the google's official `npm` package

https://googleapis.dev/nodejs/googleapis/latest/cloudidentity/classes/Cloudidentity.html
https://www.npmjs.com/package/@googleapis/cloudidentity

2025-02-24 16:22 UTC, rubentalstra commented on api/strategies/googleStrategy.js
> +}
thank you for doing this manual. but would it be possible to use the google's official `npm` package

https://googleapis.dev/nodejs/googleapis/latest/cloudidentity/classes/Cloudidentity.html
https://www.npmjs.com/package/@googleapis/cloudidentity

2025-02-24 16:22 UTC, rubentalstra commented on api/strategies/googleStrategy.js
> +}
thank you for doing this manual. but would it be possible to use the google's official `npm` package

https://googleapis.dev/nodejs/googleapis/latest/cloudidentity/classes/Cloudidentity.html
https://www.npmjs.com/package/@googleapis/cloudidentity

2025-02-24 16:22 UTC, rubentalstra commented on api/server/routes/oauth.js
> +
could we move this to the google login file? so we can keep the oauth file clean?

2025-02-24 16:22 UTC, rubentalstra commented on api/server/routes/oauth.js
> +  },
is this needed to do (req,res,next)? is this not build into passport?

2025-04-14 16:42 UTC, owengo commented on api/server/routes/oauth.js
> +  },
The requested changes are pushed; now the npm module is used and the membership verification is done in a middleware  called as callback on the oauth route

2025-05-14 15:39 UTC, rubentalstra requested changes
Please have a look at my comments. 

Thank you in advanced.

Some of your changes I do not really understand. AI??

2025-05-14 15:39 UTC, rubentalstra commented on api/server/middleware/index.js
> +  verifyGoogleGroupMembership: require('./checkGoogleGroup'),
I don't like how this is done. Please do it like how the rest is done as well.

2025-05-14 15:39 UTC, rubentalstra commented on package.json
> +    "@googleapis/cloudidentity": "^16.1.0"
Please don't place it here. Put it in the /api folder this package.

2025-05-14 15:39 UTC, rubentalstra commented on api/strategies/googleStrategy.js
??can you explain a little why you made so many changes? Are all of them needed??

2025-05-14 15:39 UTC, rubentalstra commented on api/server/routes/oauth.js
> -    scope: ['openid', 'profile', 'email'],
Can this not be just left alone?

2025-05-14 15:39 UTC, rubentalstra commented on api/server/routes/oauth.js
> -    scope: ['openid', 'profile', 'email'],
Can this not be just left alone?

2025-05-14 16:21 UTC, owengo commented on api/server/routes/oauth.js
> -    scope: ['openid', 'profile', 'email'],
we need to be able to check if the user belongs to a group.
There are two ways to do this:

1. Use a service with access to google workspace admin api
2. Use the client token with the scope: https://www.googleapis.com/auth/cloud-identity.groups.readonly. It allows to check membership of a group

For several reasons I prefer using the client token rather than a service account with administrative rights on the workspace.
More generally we could also add other scopes, for example if one day you want to be able to "connect" librechat to the client's google drive.  Here again you could prefer the service account with admin privileges on the workspace.

2025-05-14 16:33 UTC, owengo commented on api/strategies/googleStrategy.js
The idea is that we use passport functionality with a middleware chained to validate the user's membership of the group.
It was supposed to minimize the alteration of api/server/routes/oauth.js and keep most of the stuff outside the default behavior.
So yes, basically we need:

- additionnal scopes to be able to check group membership
- a middleware in passport to enforce group membership validation

as said earlier the scopes list will have further modifications when you will try to integrate with google workspace environment ( access to drive, calendar, emails, .. ).
the middleware mechanism seemed to be minimally invasive.

2026-04-11 17:55 UTC, closed without merging

2026-05-27 15:07 UTC, mirestrepo commented
This feature would be very helpful. Was it implemented somewhere else? Thank you!

2026-05-27 15:12 UTC, owengo commented
> This feature would be very helpful. Was it implemented somewhere else? Thank you!

The PR was rejected but you can find the patch on our repo:
https://github.com/danny-avila/LibreChat/compare/main...openwengo:LibreChat:main