feat: manage an 'x-strict': true attribute in openapi specs for assis…
danny-avila/LibreChat pull request #4639
Opened 2024-11-05 13:38 UTC by owengo

…tants which generates function calls with stric attribute

# Pull Request Template
⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

https://github.com/LibreChat-AI/librechat.ai/pull/162

## Summary

https://github.com/danny-avila/LibreChat/discussions/4637

By default the assistant actions are function calls not using the new "strict" mode available since structured output is available in gpt-4o.
With this patch we can use the new strict mode for assistants by simply adding a 'x-strict': true flag in the openapi spec of an action.

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

The client must have the updated data-provider package.

1. add 'x-strict': true in the openapi spec of an existing action
2. go to the https://platform.openai.com/assistants/<id  of the assistant > ( or refresh the page )
3. In the functions list click on the ones matching the change and verify
  -   "strict": true  is  present at the same level as "name"
  -  "additionalProperties": false is present in the "parameters" object

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] A pull request for updating the documentation has been submitted.

2025-02-07 02:32 UTC, danny-avila commented
Thanks, I will review this tomorrow

2025-02-07 02:33 UTC, danny-avila requested changes

2025-02-07 02:33 UTC, danny-avila commented on packages/data-provider/src/types/assistants.ts
> +    additionnalProperties?: boolean; // must be false if strict is true https://platform.openai.com/docs/guides/structured-outputs/some-type-specific-keywords-are-not-yet-supported
typo here, should be `additionalProperties`

2025-02-07 10:49 UTC, owengo commented on packages/data-provider/src/types/assistants.ts
> +    additionnalProperties?: boolean; // must be false if strict is true https://platform.openai.com/docs/guides/structured-outputs/some-type-specific-keywords-are-not-yet-supported
Sorry for this. I also ran eslint and fixed some errors & warnings.

2025-02-10 21:02 UTC, danny-avila approved these changes

2025-02-10 21:02 UTC, merged