Openid client
danny-avila/LibreChat pull request #481
Opened 2023-06-11 06:42 UTC by bsu3338

This code introduces the ability to configure OpenID as an authentication method similar to the current Google option.  
The method uses passport openid-client strategy which requires session support. For session support initially, express-session was used. Although this works for initial deployment, looking into moving to connect-mongo. 

The documentation is within the .env.example

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation update  
  

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration:
##
Tested using Azure AD

Azure AD
- Sign in to the Azure Portal
- Search for and select Azure Active Directory
- Select App registrations > New registration
- Enter a display Name
- Choose Web
- Enter https://fqdn/oauth/openid/callback
- Select Overview
- Note of the Application (client) ID and Directory (tenant) ID
- Select Authentication
- Check Access tokens and ID tokens
- Select Certificates & Secrets
- Create a secret and note the value

Edit .env to include variables
OPENID_CLIENT_ID=From Note Above
OPENID_CLIENT_SECRET=From Note Above
OPENID_ISSUER=https://login.microsoftonline.com/(tenant id)/v2.0/
OPENID_SESSION_SECRET=Random String
OPENID_SCOPE=openid profile email
OPENID_CALLBACK_URL=/oauth/openid/callback

### **Test Configuration**:
##

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-11 15:31 UTC, danny-avila commented
@bsu3338 thanks for this. be advised, I rebased your branch so it's up to date with the main branch.

2023-06-11 15:33 UTC, danny-avila commented on docker-compose.yml
I need to fix the example you copied, but the build arg should actually be commented out if the default value is false.

2023-06-11 18:34 UTC, danorlando commented on api/server/index.js
> +    app.use(session({
I noticed that this seems to be using both JWT and sessions, but api's are authenticated by the JWT token. I had actually pulled out the use of sessions in favor JWT tokens as they are generally more secure. I'm not sure I'm following exactly how the session is being used... is that for validation from the 3rd party provider? If you could help clarify this, that would be great. thanks.

2023-06-11 18:37 UTC, danorlando commented on client/src/data-provider/api-endpoints.ts
> +export const loginOpenID = () => {
Where is this being used?

2023-06-11 21:18 UTC, ClaraLeigh requested changes

2023-06-11 21:18 UTC, ClaraLeigh commented on .env.example
> +VITE_SHOW_OPENID_LOGIN_OPTION=false
Minor one, but could you change this to `ALLOW_OPENID` or maybe `ALLOW_OPENID_LOGIN`? 
I want to change the google one too (in the future) but anything with the prefix `ALLOW_` will be passed to vite and it saves changing it in the future if we stop using vite. 

Side note: shorter env var names is something I'm pushing for a little more in projects as certain platforms (ie. AWS lambda) have a limited number of characters in `.env` files

2023-06-11 21:18 UTC, ClaraLeigh commented on .env.example
> +VITE_SHOW_OPENID_LOGIN_NAME=OpenID
This one could be simplified slightly too. I think `VITE_OPENID_NAME` or `SCRIPT_OPENID_NAME` would probably work. Just slightly less characters

2023-06-11 21:18 UTC, ClaraLeigh commented on api/strategies/openidStrategy.js
> +              // avatar: userinfo.picture
This looks like valid/commented out code. Just checking if we can indeed pull in the user avatar? 
(x2 for the other time this occurs slightly further down)

2023-06-11 21:18 UTC, ClaraLeigh commented on .env.example
> +VITE_SHOW_OPENID_LOGIN_NAME=OpenID
Side note: do we need this at all? Is it common for people to rename OpenID to something else? I might even suggest removing this as an option and using "OpenID" instead in the code (or at the very least having it default to "OpenID" if it's left blank

2023-06-11 21:18 UTC, ClaraLeigh commented on .env.example
> +OPENID_SCOPE=openid profile email
I believe this will have to be wrapped in quotes as it contains spaces: `OPENID_SCOPE="openid profile email"`

2023-06-11 21:18 UTC, ClaraLeigh commented on api/strategies/openidStrategy.js
> +          let user = await User.findOne({ email: userinfo.email });
Just confirming for security as I don't know much about its inner workings, can OpenID be trusted to only have verified email accounts? I'm assuming so but just wanted to double check

2023-06-12 05:33 UTC, ClaraLeigh reviewed
I'm guessing you are still working on this as there are some changes only half done. lmk when you need another review :)

2023-06-12 05:33 UTC, ClaraLeigh commented on client/src/components/Auth/Registration.tsx
> +              <p>{ALLOW_OPENID}</p>
Thinking this is a typo and it should just say "OpenID" ?

2023-06-12 05:33 UTC, ClaraLeigh commented on client/src/components/Auth/Login.tsx
> +              <p>{ALLOW_OPENID}</p>
same here: Thinking this is a typo and it should just say "OpenID" ?

2023-06-12 06:31 UTC, closed without merging

2023-06-12 06:31 UTC, bsu3338 commented
Going back to clean some things up and will request once it is a little cleaner

2023-06-12 14:18 UTC, danny-avila commented
> Going back to clean some things up and will request once it is a little cleaner

Take your time and thanks for working on this! It's definitely a need as it was just requested in #489

2023-06-12 15:25 UTC, danorlando commented
> Going back to clean some things up and will request once it is a little cleaner

Yea, just to reiterate what Danny said. Its definitely a valuable contribution, so thanks for working on it.