Add new LLM API Provider: Novita AI
danny-avila/LibreChat pull request #5115
Opened 2024-12-27 11:54 UTC by vercelInfrAI

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

### **Test Configuration**:

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2025-01-15 18:26 UTC, danny-avila requested changes
To merge this PR, please take the time to read and implement my requested changes, fill out the PR template and provide an appropriate semantic title for the PR.

Also, submit a relevant PR to https://github.com/LibreChat-AI/librechat.ai (docs) if you haven't already.

2025-01-15 18:26 UTC, danny-avila commented on README.md
> +    - OpenRouter, [Novita AI](https://novita.ai/llm-api?utm_source=github_librecha&utm_medium=github_readme&utm_campaign=github_link), Perplexity, ShuttleAI, Deepseek, Qwen, and more
Please remove this.

2025-01-15 18:26 UTC, danny-avila commented on api/utils/tokens.spec.js
> +  test('should return correct tokens for partial match (NovitaAI)', () => {
this change is unnecessary

2025-01-15 18:26 UTC, danny-avila commented on client/public/assets/novita.png
Please make this a 1 kb icon

2025-01-15 18:26 UTC, danny-avila commented on client/public/assets/novita.png
preferably SVG

2025-01-15 18:26 UTC, danny-avila commented on client/src/components/Chat/Menus/Endpoints/UnknownIcon.tsx
> +  [KnownEndpoints.novitaai]: '/assets/novita.png',
SVG

2025-01-15 18:26 UTC, danny-avila commented on client/src/utils/convos.fakeData.ts
> +          chatGptLabel: null,
unnecessary

2025-01-15 18:26 UTC, danny-avila commented on librechat.example.yaml
> +    # Novita Example
unnecessary

2025-04-09 14:06 UTC, closed without merging

2025-06-29 10:05 UTC, schaze commented
@danny-avila: Is there any reason why this was not merged? I can't seem to find any response to this.