fix: #546 issue with closing registration
danny-avila/LibreChat pull request #547
Opened 2023-06-24 18:15 UTC by danorlando

Fixes issue #546 where closing registration was no longer working.
Also renames some controller files for consistency.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Set ALLOW_REGISTRATION to false and verify that registration is not possible. Then set it to true and make sure it works. Also manually entered /register path in url bar to make sure that it reroutes to /login when registration is disabled.

2023-06-24 19:59 UTC, fuegovic approved these changes
I tested and can confirm that the fix is working

2023-06-25 02:52 UTC, bsu3338 commented
I just saw openid merged. It will need the same fix in the Login to be consistent with google auth in this PR
 === true

2023-06-25 03:12 UTC, danny-avila requested changes

2023-06-25 03:12 UTC, danny-avila commented on client/src/components/Auth/Registration.tsx
As @bsu3338 mentioned, the openId auth handling needs to be added and then this all set to go!

2023-06-25 18:50 UTC, danorlando commented on client/src/components/Auth/Registration.tsx
This can be merged now.

2023-06-25 19:40 UTC, danny-avila approved these changes

2023-06-25 19:40 UTC, merged