Site Crawler Plugin with puppeteer for dynamic Sites
danny-avila/LibreChat pull request #758
Opened 2023-08-05 08:00 UTC by SphaeroX

related to https://github.com/danny-avila/LibreChat/issues/581

my coding skills are not the best and i tried to write the plugin for librechat, i hope it helps.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

  

## How Has This Been Tested?

-

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-05 11:16 UTC, SphaeroX commented
there are some troubles on my vserver (ubuntu with root) with puppeteer

2023-08-05 14:20 UTC, danny-avila commented
To really match what ChatGPT does, we could have a suite of tools per the browser instructions: https://pbs.twimg.com/media/FsFJZk4XoAMJsJY?format=jpg&name=large

This is a good start though and improves what we already have! I will have to tweak it to make it more dynamic, and to use embeddings as well

2023-08-06 00:33 UTC, danny-avila requested changes

2023-08-06 00:33 UTC, danny-avila commented on api/app/clients/tools/SiteCrawler.js
> +const puppeteer = require('puppeteer');
You should the web loader from langchain here, it may be more efficient with memory 

https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/web_puppeteer

2023-08-06 00:34 UTC, danny-avila requested changes

2023-08-06 00:34 UTC, danny-avila commented on package.json
> +    "puppeteer": "^19.11.1"
this should not be installed in the root package file, it should be installed from the ./api/ folder.

 you will have to uninstall from the root `npm uninstall langchain` 
 
 then cd `./api/` and install

2023-08-06 15:49 UTC, danny-avila commented on package.json
> +    "puppeteer": "^19.11.1"
sorry I was half asleep and I wrote the wrong package, edited my comment above. to clarify, I meant just the puppeteer package

2023-09-19 04:28 UTC, SphaeroX commented
closed because coding sklills are not enough for that ^^ sorry

2023-09-19 04:28 UTC, closed without merging