added icons for chat identification
danny-avila/LibreChat pull request #879
Opened 2023-09-05 22:39 UTC by Berry-13

## Summary

added an icon to the left of each chat to better identify the endpoint

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Testing

check if all the icon render and works correctly

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

2023-09-12 15:51 UTC, danny-avila commented
Maybe I'm being nitpicky, but it looks like the title text is now further to the right from the icons with your changes. any way we can have more space for the title? 

![image](https://github.com/danny-avila/LibreChat/assets/110412045/c31a31d5-b81a-47ca-a598-ef5eec82b23c)

2023-09-12 15:56 UTC, Berry-13 commented
Done!

![image](https://github.com/danny-avila/LibreChat/assets/81851188/b14fee2b-0a73-4ac1-9c1a-0374e902fa16)

2023-09-13 16:02 UTC, danny-avila requested changes

2023-09-13 16:02 UTC, danny-avila commented on client/src/components/Endpoints/getMinimalIcon.tsx
> +interface IconProps {
repeated here and in getIcon, should be imported from ~/common

2023-09-13 16:02 UTC, danny-avila commented on client/src/components/Endpoints/getMinimalIcon.tsx
> +      const { chatGptLabel } = props;
repetitive code deconstructing the same variables. I would prefer you not use the chained if/else-if statements in favor of a map. see client/src/components/Input/ModelSelect/ModelSelect.tsx for an example

2023-09-13 16:02 UTC, danny-avila commented on client/src/components/Endpoints/getIcon.tsx
> +    } else if (endpoint === 'openAI') {
do you mind fixing getIcon to match getMinimalIcon in structure? we can take this opportunity to clean up the code here

2023-09-13 19:29 UTC, danny-avila requested changes

2023-09-13 19:29 UTC, danny-avila commented on client/src/components/Endpoints/getIcon.tsx
> +    switch (endpoint) {
switch/case should never be used, you won't find it in this project: https://javascript.plainenglish.io/why-you-should-avoid-switch-statements-in-javascript-ce07d5b60da4

2023-09-13 19:29 UTC, danny-avila commented on client/src/components/Endpoints/getIcon.tsx
> +        const { chatGptLabel } = props;
also you are still running in the problem I outlined.

```js
const { chatGptLabel } = props;
...
const { chatGptLabel } = props;
...
const { chatGptLabel } = props;
...
const { chatGptLabel } = props;
```

I know this was here before but now is the opportunity to fix it

2023-09-13 19:29 UTC, danny-avila commented on client/src/components/Endpoints/getMinimalIcon.tsx
> +    switch (endpoint) {
no switch/case, use a map like in the original example I gave

2023-09-14 15:43 UTC, Berry-13 commented
in the meantime I also removed some unnecessary functions in getMinimalistIcon

2023-09-14 16:48 UTC, danny-avila approved these changes

2023-09-14 16:48 UTC, danny-avila commented on client/src/components/Endpoints/getIcon.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
One last thing, I just noticed this eslint disable line. This and the minimalist function are already structured like React functional components so we should just make them. Rename it to Icon.tsx and the function as well, remove the comment and treat it like a regular React.FC(which it even has a type for).

2023-09-14 16:49 UTC, danny-avila requested changes

2023-09-14 16:49 UTC, danny-avila commented on client/src/components/Endpoints/getIcon.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
One last thing, I just noticed this eslint disable line. This and the minimalist function are already structured like React functional components so we should just make them. Rename it to Icon.tsx and the function as well, remove the comment and treat it like a regular React.FC(which it even has a type for).

2023-09-14 16:49 UTC, danny-avila commented
thank you, the code is a lot cleaner now. I think the change to Icon.tsx and MinimalistIcon.tsx as React FC's is all that's left. Good work on this!

2023-09-18 19:21 UTC, danny-avila approved these changes

2023-09-18 19:21 UTC, merged